config/routes.rb
Translatio::Application.routes.draw do
  get "recordings/index"
  get "recordings/create"
  
  get "participants/create"
  get "participants/list"

  get "logs/list"
  get "logs/create"
  
  resources :conferences
  resources :languages
  resources :users
  resources :translations
  resources :participants

  get "translation/index"
  get "translation/begin"
  root :to => "translation#index"
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  # GET /languages
  # GET /languages.xml
  def index
    @languages = Language.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @languages }
    end
  end

  # GET /languages/1
  # GET /languages/1.xml
  def show
    @language = Language.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @language }
    end
  end

  # GET /languages/new
  # GET /languages/new.xml
  def new
    @language = Language.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @language }
    end
  end

  # GET /languages/1/edit
  def edit
    @language = Language.find(params[:id])
  end

  # POST /languages
  # POST /languages.xml
  def create
    @language = Language.new(params[:language])

    respond_to do |format|
      if @language.save
        format.html { redirect_to(@language, :notice => 'Language was successfully created.') }
        format.xml  { render :xml => @language, :status => :created, :location => @language }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @language.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /languages/1
  # PUT /languages/1.xml
  def update
    @language = Language.find(params[:id])

    respond_to do |format|
      if @language.update_attributes(params[:language])
        format.html { redirect_to(@language, :notice => 'Language was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @language.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1
  # DELETE /languages/1.xml
  def destroy
    @language = Language.find(params[:id])
    @language.destroy

    respond_to do |format|
      format.html { redirect_to(languages_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/languages/_form.html.erb
<%= form_for(@language) do |f| %>
  <% if @language.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@language.errors.count, "error") %> prohibited this language from being saved:</h2>

      <ul>
      <% @language.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/languages/edit.html.erb
<h1>Editing language</h1>

<%= render 'form' %>

<%= link_to 'Show', @language %> |
<%= link_to 'Back', languages_path %>

app/views/languages/index.html.erb
<h1>Listing languages</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @languages.each do |language| %>
  <tr>
    <td><%= language.name %></td>
    <td><%= link_to 'Show', language %></td>
    <td><%= link_to 'Edit', edit_language_path(language) %></td>
    <td><%= link_to 'Destroy', language, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Language', new_language_path %>

app/views/languages/new.html.erb
<h1>New language</h1>

<%= render 'form' %>

<%= link_to 'Back', languages_path %>

app/views/languages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @language.name %>
</p>


<%= link_to 'Edit', edit_language_path(@language) %> |
<%= link_to 'Back', languages_path %>